default: &default
  adapter: postgresql
  user: postgres
  password: kikidoyouloveme009
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: active_storage_api_development

test:
  <<: *default
  database: active_storage_api_test